
#' Phyologenetic regionalization
#'
#' @param ps A `phylospatial` object. If \code{method} is anything other than \code{"kmeans"}, it must contain a
#'    `dissim` component generated by \link{ps_add_dissim}.
#' @param k Number of spatial clusters to divide the region into (Positive integer).
#' @param method Clustering method. Options include \code{"kmeans"} and any methods listed under \link[stats]{hclust}.
#' @param endemism Logical indicating whether community values should be divided by column totals (taxon range sizes)
#'    to derive endemism. Only used if \code{method = "kmeans"}; in other cases this information should instead be
#'    supplied to \link{ps_add_dissim}.
#' @param normalize Logical indicating whether community values should be divided by row totals (community sums). If `TRUE`,
#'    dissimilarity is based on proportional community composition. This happens after endemism is derived. Only used if
#'    \code{method = "kmeans"}; in other cases this information should instead be supplied to \link{ps_add_dissim}.
#'
#' @return A raster or matrix with an integer indicating which of the \code{k} regions each site belongs to.
#' @export
ps_regions <- function(ps, k = 5, method = "kmeans", endemism = FALSE, normalize = TRUE){

      enforce_ps(ps)

      # sites with taxa
      r <- a <- occupied(ps)

      if(method == "kmeans"){
            comm <- ps$comm[a,]
            if(endemism) comm <- apply(comm, 2, function(x) x / sum(x))
            if(normalize) comm <- t(apply(comm, 1, function(x) x / sum(x)))
            comm[!is.finite(comm)] <- 0
            regions <- stats::kmeans(comm, k)$cluster
      }else{
            stopifnot("Input data set contains no `dissim` data, which is required for methods other than `kmeans`; add it first using `ps_add_dissim()`." = !is.null(ps$dissim))
            d <- as.matrix(ps$dissim)
            rownames(d) <- colnames(d) <- paste("cell", 1:ncol(d))
            da <- d[a, a]

            # sites fully segregated by the 2 basal clades have Inf distance;
            # set distance to value greater than max observed distance
            da[is.infinite(da)] <- max(da[!is.infinite(da)]) + 1000
            da <- stats::as.dist(da)

            clust <- stats::hclust(da, method = method)
            regions <- stats::cutree(clust, k)
      }

      r[a] <- regions
      r[!a] <- NA

      if(!is.null(ps$spatial)){
            r <- matrix(r, ncol = 1)
            colnames(r) <- "phyloregion"
            return(to_spatial(r, ps$spatial))
      }else{
            return(r)
      }

}
